/**
 * Taiwan Stock API Integration (TWSE & TPEx)
 * Adapts local stock data to match BingX API interface for the app.
 */

const StockAPI = {
    // Cache
    cachedSymbols: [],
    lastSymbolFetch: 0,
    CACHE_DURATION: 1000 * 60 * 5, // 5 minutes

    // CORS Proxies for Yahoo Finance
    CORS_PROXIES: [
        'https://api.allorigins.win/raw?url=',
        'https://corsproxy.io/?',
        'https://api.codetabs.com/v1/proxy?quest=',
        'https://thingproxy.freeboard.io/fetch/'
    ],
    currentProxyIndex: 0,

    /**
     * Request with robust CORS handling and proxy rotation
     */
    async request(url) {
        // 1. If it's a relative URL (like ./tw_stocks.json), fetch directly
        if (!url.startsWith('http')) {
            const response = await fetch(url, { cache: 'no-store' });
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            return await response.json();
        }

        // 2. Try direct fetch first for external APIs
        try {
            const response = await fetch(url, { cache: 'no-store' });
            if (response.ok) return await response.json();
        } catch (e) {
            console.log('Direct fetch failed, falling back to proxies for:', url);
        }

        // 3. Fallback to Proxy Rotation
        for (let attempt = 0; attempt < this.CORS_PROXIES.length; attempt++) {
            const proxyIndex = (this.currentProxyIndex + attempt) % this.CORS_PROXIES.length;
            const proxyUrl = this.CORS_PROXIES[proxyIndex] + encodeURIComponent(url);

            try {
                const controller = new AbortController();
                const timeoutId = setTimeout(() => controller.abort(), 8000); // 8-second timeout

                const response = await fetch(proxyUrl, { cache: 'no-store', signal: controller.signal });
                clearTimeout(timeoutId);

                if (response.ok) {
                    this.currentProxyIndex = proxyIndex; // Save the working proxy
                    return await response.json();
                }
            } catch (error) {
                console.warn(`Proxy ${proxyIndex + 1} failed for Stock API.`);
            }
        }

        throw new Error('All CORS proxies failed for Stock API request.');
    },

    /**
     * Get all listed stocks from TWSE and TPEx
     */
    async getSymbols(boardType = 'MAINBOARD') {
        try {
            // Fetch the static JSON generated by our GitHub Action, bypassing CDN cache
            const data = await this.request(`./tw_stocks.json?_t=${Date.now()}`);
            
            let filteredSymbols = [];

            if (boardType) {
                filteredSymbols = data.filter(s => s.board === boardType);
            } else {
                filteredSymbols = data;
            }
            
            this.cachedSymbols = filteredSymbols.length > 0 ? filteredSymbols : data;
            return this.cachedSymbols;
        } catch (error) {
            console.error('Failed to load static TW stocks JSON', error);
            throw new Error('Failed to load Taiwan Stocks data. Please ensure the GitHub action has run.');
        }
    },

    /**
     * Get Ticker via Yahoo Finance Quote API
     */
    async get24hrTicker(symbol) {
        if (this.cachedSymbols.length === 0) {
            await this.getSymbols();
        }

        const stock = this.cachedSymbols.find(s => s.symbol === symbol);
        if (!stock) return null;
        const type = stock ? stock.raw.type : 'TWSE'; // Default to TWSE
        const yahooSymbol = type === 'TWSE' ? `${symbol}.TW` : `${symbol}.TWO`;

        try {
            // Fetch live/delayed quote from Yahoo Finance
            const url = `https://query1.finance.yahoo.com/v7/finance/quote?symbols=${yahooSymbol}`;
            const res = await this.request(url);
            
            if (!res.quoteResponse || !res.quoteResponse.result || res.quoteResponse.result.length === 0) {
                throw new Error("No quote data returned");
            }

            const quote = res.quoteResponse.result[0];

            return {
                symbol: symbol,
                lastPrice: quote.regularMarketPrice || 0,
                priceChangePercent: quote.regularMarketChangePercent || 0,
                highPrice: quote.regularMarketDayHigh || 0,
                lowPrice: quote.regularMarketDayLow || 0,
                quoteVolume: quote.regularMarketVolume || 0,
                volume: quote.regularMarketVolume || 0
            };
        } catch (e) {
            console.warn(`Failed to fetch live quote for ${symbol} from Yahoo, using local fallback`, e);
            
            // Fallback to local daily data for Warrants/Bonds that Yahoo ignores
            const r = stock.raw;
            
            // Support both new Normalized keys and old raw keys, stripping commas safely
            const closeStr = r.NormalizedClose || r.ClosingPrice || r.Close || r.LatestPrice || "0";
            const changeStr = r.NormalizedChange || r.Change || "0";
            const highStr = r.NormalizedHigh || r.HighestPrice || r.High || "0";
            const lowStr = r.NormalizedLow || r.LowestPrice || r.Low || "0";
            const volStr = r.NormalizedVolume || r.TradeVolume || r.TradingVolume || r.Volume || "0";

            const close = parseFloat(String(closeStr).replace(/,/g, '')) || 0;
            const change = parseFloat(String(changeStr).replace(/,/g, '')) || 0;
            const prevClose = close - change;
            
            return {
                symbol: symbol,
                lastPrice: close,
                priceChangePercent: prevClose !== 0 ? (change / prevClose) * 100 : 0,
                highPrice: parseFloat(String(highStr).replace(/,/g, '')) || 0,
                lowPrice: parseFloat(String(lowStr).replace(/,/g, '')) || 0,
                quoteVolume: parseFloat(String(volStr).replace(/,/g, '')) || 0,
                volume: parseFloat(String(volStr).replace(/,/g, '')) || 0
            };
        }
    },

    async getAll24hrTickers() {
        if (this.cachedSymbols.length === 0) {
            await this.getSymbols();
        }

        // Rely purely on the local JSON data for the screener to prevent massive Yahoo API URL crashes
        return this.cachedSymbols.map(stock => {
            const r = stock.raw;
            
            // Support both new Normalized keys and old raw keys, stripping commas safely
            const closeStr = r.NormalizedClose || r.ClosingPrice || r.Close || r.LatestPrice || "0";
            const changeStr = r.NormalizedChange || r.Change || "0";
            const highStr = r.NormalizedHigh || r.HighestPrice || r.High || "0";
            const lowStr = r.NormalizedLow || r.LowestPrice || r.Low || "0";
            const volStr = r.NormalizedVolume || r.TradeVolume || r.TradingVolume || r.Volume || "0";

            const close = parseFloat(String(closeStr).replace(/,/g, '')) || 0;
            const change = parseFloat(String(changeStr).replace(/,/g, '')) || 0;
            const prevClose = close - change;
            
            return {
                symbol: stock.symbol,
                industry: stock.industry || '未分類',
                lastPrice: close,
                priceChangePercent: prevClose !== 0 ? (change / prevClose) * 100 : 0,
                highPrice: parseFloat(String(highStr).replace(/,/g, '')) || 0,
                lowPrice: parseFloat(String(lowStr).replace(/,/g, '')) || 0,
                quoteVolume: parseFloat(String(volStr).replace(/,/g, '')) || 0
            };
        });
    },

    /**
     * Get Historical Data (Klines)
     * Fetches monthly data from TWSE/TPEx and stitches it.
     */
    async getKlines(symbol, interval, limit = 200) {
        // Determine type (TWSE or TPEx)
        if (this.cachedSymbols.length === 0) await this.getSymbols();
        const stock = this.cachedSymbols.find(s => s.symbol === symbol);
        const type = stock ? stock.raw.type : 'TWSE'; // Default to TWSE if unknown

        // Format symbol for Yahoo Finance (2330.TW for TWSE, XXXX.TWO for TPEx)
        const yahooSymbol = type === 'TWSE' ? `${symbol}.TW` : `${symbol}.TWO`;

        // Map BingX intervals to Yahoo Finance intervals
        const intervalMap = {
            '1m': '1m', '5m': '5m', '15m': '15m', '30m': '30m',
            '1h': '60m', '4h': '1d', // Yahoo doesn't perfectly support 4h, default to daily
            '1d': '1d', '1w': '1wk'
        };
        
        const yInterval = intervalMap[interval] || '1d';
        
        // Define range based on interval (Intraday is limited to 1 month on Yahoo)
        let range = '1y'; 
        if (['1m', '5m', '15m', '30m', '60m'].includes(yInterval)) range = '1mo';
        else if (yInterval === '1wk') range = '5y';

        try {
            const url = `https://query1.finance.yahoo.com/v8/finance/chart/${yahooSymbol}?interval=${yInterval}&range=${range}`;
            const res = await this.request(url);

            if (!res.chart || !res.chart.result || res.chart.result.length === 0) {
                throw new Error("No data returned from Yahoo Finance");
            }

            const result = res.chart.result[0];
            const timestamps = result.timestamp;
            const quote = result.indicators.quote[0];

            if (!timestamps || !quote) return [];

            const klines = [];
            for (let i = 0; i < timestamps.length; i++) {
                // Skip null values (common during market halts or holidays)
                if (quote.close[i] === null) continue;

                klines.push({
                    time: timestamps[i] * 1000, // Convert unix seconds to ms
                    open: quote.open[i],
                    high: quote.high[i],
                    low: quote.low[i],
                    close: quote.close[i],
                    volume: quote.volume[i] || 0
                });
            }

            // Return the requested limit of candles
            return klines.slice(-limit);

        } catch (e) {
            console.warn(`Failed to fetch klines for ${symbol} via Yahoo Finance`, e);
            throw e;
        }
    },

    // Search
    searchSymbols(query) {
        if (!query) return [];
        const q = query.toUpperCase();
        return this.cachedSymbols.filter(s =>
            String(s.symbol).toUpperCase().includes(q) ||
            (s.baseAsset && String(s.baseAsset).toUpperCase().includes(q))
        ).slice(0, 15);
    },

    // Formatter
    formatSymbol(symbol) {
        const s = this.cachedSymbols.find(x => x.symbol === symbol);
        return s ? `${s.symbol} ${s.baseAsset}` : symbol;
    },

    formatPrice(price) {
        return price.toFixed(2);
    },

    formatNumber(num) {
        if (num >= 1e9) return (num / 1e9).toFixed(2) + 'B';
        if (num >= 1e6) return (num / 1e6).toFixed(2) + 'M';
        if (num >= 1e3) return (num / 1e3).toFixed(2) + 'K';
        return num.toFixed(0);
    },

    formatPercent(val) {
        return (val >= 0 ? '+' : '') + val.toFixed(2) + '%';
    },

    delay(ms) {
        return new Promise(r => setTimeout(r, ms));
    }
};

window.StockAPI = StockAPI;
